# Generated by Django 3.2.9 on 2021-12-09 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macm',
            name='asset_type',
        ),
        migrations.AddField(
            model_name='macm',
            name='asset_types',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
