# Generated by Django 2.2.12 on 2022-01-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_macm_asset_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macm',
            name='custom_types',
        ),
        migrations.AlterField(
            model_name='asset_type',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='macm',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
